### ISSUE TITLE
Error: Module jupyter-matplotlib, semver range ^0.5.0 is not registered as a widget module

### ISSUE THREAD

**Issue by mfrawley** [matplotlib/ipympl#161]
I nearly went crazy trying to figure this out, I don't know if it's intentional but the version of the nodejs package (under js) in master is 0.5.0, whereas the overall python/conda package version was 0.4.0. 
  When installing the extension without specifying any specific version in a fresh conda environment (via docker) the above is happening every time. Using the update GUI in jupyter lab's extension manager seems to have resolved. Hope this helps someone.

**Comment by martinRenou** [comment]
It is intentional that the front-end version and the back-end versions are different. They have diverged at some point in the development (I guess at some point the front-end had lots of development while the back-end did not change at all).

As said in the README, if you install jupyter-matplotlib for JupyterLab, you need to install the JupyterLab extension from the GUI or running:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
```

So, using conda, you need to run the following in a fresh environment:
```
conda install -c conda-forge ipympl nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
```

Would you mind if we close issue? I feel like it's working as intended.

**Comment by mfrawley** [comment]
Hi @martinRenou but I did install it as you state, and got the error, here is end of my Dockerfile:

```
RUN conda install -c conda-forge widgetsnbextension
RUN conda install -c conda-forge ipywidgets
RUN conda install -c conda-forge ipympl
RUN jupyter labextension install --minimize=False @jupyter-widgets/jupyterlab-manager
RUN jupyter labextension install --minimize=False jupyter-matplotlib
```
I set minimize=False to make the build faster but it has nothing to do with the issue.

**Comment by martinRenou** [comment]
Mmh, what happens if you enforce the version with:
```
RUN jupyter labextension install --minimize=False jupyter-matplotlib@0.5
```

**Comment by mfrawley** [comment]
No, alas, after trying that the extension manager shows the Update link just as it did before and I get the same error.

**Comment by martinRenou** [comment]
> Perhaps this is specific to operation inside Docker

That was what I wanted to say. It's not the first time I see this kind of comment when using Docker and JupyterLab (see https://github.com/jupyter-widgets/ipywidgets/issues/2623).

- What happens if you simply refresh the page? Does it find the extension?

- Do core widgets work?
```Python
from ipywidgets import Button
Button(description='test')
```

**Comment by mfrawley** [comment]
- Do core widgets work?
```
from ipywidgets import Button
Button(description='test')
```

The above works..the code I was having the error when trying to plot was more or less:
```
plt.figure(1, figsize=(9,5))
plt.plot(df[['foo', 'bar']).resample('1W').count())
plt.tight_layout()
plt.show()
```
Where df is a pandas dataframe with a datetime index.

- What happens if you simply refresh the page? Does it find the extension?
No, it makes no difference.

**Comment by mfrawley** [comment]
Self-contained example:
```
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({'a': [1,2,3]})

plt.figure(2)
plt.plot(df['a'])
plt.show()
```
This gives "Loading widget" but the same JS exception as the title of this issue.

**Comment by mfrawley** [comment]
I appreciate the help but now even the GUI solution isn't working ..I might be unresponsive for a few days but would be willing to try to debug in the future.

**Comment by martinRenou** [comment]
I am clueless right now. I guess I will have to try it myself at some point. Maybe it would be good to add that to documentation somewhere (Simple Dockerfile with ipywidgets and some other widgets libraries running in JupyterLab)

**Comment by slopedog** [comment]
I've got this problem, too (same error in console). It was working before, and it died without my changing anything. I can trigger it with
```python3
# %matplotlib widget
import matplotlib.pyplot as plt

plt.figure()
plt.plot([1,2])
plt.show()
```

Since then, I tried:

```bash
pip uninstall -y ipywidgets ipympl
pip freeze | grep jupy | xargs pip uninstall -y
pip install ipympl ipywidgets jupyterlab --upgrade
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
jupyter lab
```

But this doesn't fix anything. Removing my `~/.jupyter` doesn't help, either.
I have these versions of things:

```
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyterlab==1.2.4
jupyterlab-server==1.0.6
ipykernel==5.1.3
ipympl==0.4.0
ipywidgets==7.5.1
matplotlib==3.1.2
```

```
JupyterLab v1.2.4
Known labextensions:
   app dir: /home/jah/Hank/RadioInversion2/Python/env/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyter-matplotlib v0.5.0  enabled  OK

Uninstalled core extensions:
    jupyter-matplotlib
```

That strange "Uninstalled core extensions" popped up when I tried using the GUI to install and uninstall jupyter-matplotlib, I think... I can't figure out a way to get rid of it.

**Comment by slopedog** [comment]
Oh - I probably left out the most important thing - I'm not using Docker. This is in a virtualenv on Ubuntu 18.04.

**Comment by AllanChain** [comment]
In my case (JupyterLab 2.1.0), I installed ipympl v0.5.0 months ago, and recently installed jupyter-matplotlib@0.7.2, causing the verion problem `Module jupyter-matplotlib, semver range ^0.6.0 is not registered as a widget module`. It's strange that upgrading ipympl to v0.5.6 and reinstall labextension solved the problem, but downgrading jupyter-matplotlib to 0.6.0 did not...

**Comment by apoorvmote** [comment]
I was in similar situation. It started failing after I updated juypter lab. I had to force reinstall `ipympl` as follows
```
pip3 install -I ipympl
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
jupyter lab build
```
After that it started working

**Comment by martinRenou** [comment]
> @AllanChain It's strange that upgrading ipympl to v0.5.6 and reinstall labextension solved the problem, but downgrading jupyter-matplotlib to 0.6.0 did not...

This is because jupyter-matplotlib 0.6.0 does not work on Jupyterlab 2:
https://github.com/matplotlib/ipympl#install-an-old-jupyterlab-extension

**Comment by martinRenou** [comment]
To anyone coming to this issue for related problems, please check that you have the right versions compatible with your JupyterLab version looking at this table: https://github.com/matplotlib/ipympl#install-an-old-jupyterlab-extension 

If you still have an issue please open your own issue.

**Comment by stefaneidelloth** [comment]
Please update the table. What are the versions that are compatible to the latest version of JupyterLab 2 (=2.9.9)? Can I use matplotlib 3.3.3?

**Comment by martinRenou** [comment]
The table is updated. Either you use the latest ipympl and can use it in JupyterLab 3 and 2 (for JupyterLab 2 you will need to manually install the labextension), or you take one table row and pin all the versions.

**Comment by stefaneidelloth** [comment]
If I understand you correctly, I can not use matplotlib 3.3.3 but the combination of

JupyterLab=2.2.9
Matplotlib=3.3.1
ipympl=0.5.8
jupyter-matplotlib=0.7.4

should work. Well, it doesnt. I get

jupyter-matplotlib, semver range ^0.8.2 is not registered as a widget module


(I do not use JupyterLab >=3.0.0 yet, because some extensions are not ready for it, e.g. GIT-Extension)

**Comment by martinRenou** [comment]
> jupyter-matplotlib, semver range ^0.8.2 is not registered as a widget module

This is odd, if you really have ipympl=0.5.8 you should not see this message. Can you install jupyter-matplotlib 0.8.2 like it is saying?

**Comment by stefaneidelloth** [comment]
![image](https://user-images.githubusercontent.com/12675339/104571562-88a94100-5653-11eb-936b-03cfb9b0b645.png)
![image](https://user-images.githubusercontent.com/12675339/104571752-c312de00-5653-11eb-9635-6c29e8630733.png)

**Comment by martinRenou** [comment]
Ok sorry, this is totally expected.

You don't have ipympl 0.5.8 like you are saying, you have ipympl 0.6.2, so please downgrade it and install jupyter-matplotlib 0.7.4 like the table is saying.

**Comment by stefaneidelloth** [comment]
Well, pip list said I do have ipympl 0.5.8. I'll try again...

**Comment by martinRenou** [comment]
Can you run 
```
from ipympl import _version
print(_version.version_info)
```

In your notebook?

**Comment by thomasaarholt** [comment]
I would also compare the following python and terminal commands:
```python
# in python
import ipympl
print(ipympl.__path__)
```
```bash
in bash:
which pip
which jupyter
```

My first guess is that the notebook instance you're creating is not from the same python instance that pip installed ipympl 0.5.8 into.

On my computer, they are:

```bash
['C:\\Users\\thomasaar\\Miniconda3\\envs\\py\\lib\\site-packages\\ipympl']
# I'm using bash on windows, so windows paths look funny
/c/Users/thomasaar/Miniconda3/envs/py/Scripts/pip
/c/Users/thomasaar/Miniconda3/envs/py/Scripts/jupyter
```
You can see from the path that all of these packages exist in the `py` anaconda environment.

**Comment by stefaneidelloth** [comment]
Thanks a lot for helping my clarifying my issue. You are right. I mixed some consoles. I'll try again after finishing a meeting and let you know if it works.
