### ISSUE TITLE
jupyterlab-matplotlib don't show  figure in cell

### ISSUE THREAD

**Issue by ConyKitty** [matplotlib/ipympl#162]
I'm new to jupyter lab, and I installed jupyter-matplotlib and in jupyterlab, plt.plot() some data, but nothing shown in cell, no error occurs too. Environments as below:
`JupyterLab v1.2.4`
`Known labextensions:`
  ` app dir: D:\Miniconda3\share\jupyter\lab`
       ` @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok`
        `@jupyterlab/git v0.9.0 enabled  ok`
       ` jupyter-matplotlib v0.4.0 enabled  ok`
      `  nbdime-jupyterlab v1.0.0 enabled  ok`
I have down updated the jupyter-matplotlib from v0.5.0 to v0.4.0, it doesn't work.
`ipympl                    0.3.3`
`jupyterlab                1.2.4`
![image](https://user-images.githubusercontent.com/44704127/72214572-e6d2ae00-353f-11ea-863a-332e7af6aeb3.png)
after`plt.plot([1,2,3,4])`, only `[<matplotlib.lines.Line2D at 0x1f1ed54b108>] `shown, no figure shown, and `plt.show()` doesn't work too, no response.
I very much appreciate that someone can help me to display the interactive figure in the cell, thanks!

**Comment by thomasaarholt** [comment]
Hi @ConyKitty, would you mind updating to the latest ipympl and jupyterlab and trying again? There are some major changes.

**Comment by trenton3983** [comment]
I experience the same issue with her code.
matplotlib version 3.1.3
Jupyter Lab version 1.2.6
Python version 3.7.7

**Comment by moira92** [comment]
I'm having a similar problem. I run the entire notebook and no figure appears, the first figure cell shows the following message: 

<img width="496" alt="Capture" src="https://user-images.githubusercontent.com/10518736/114843935-9d27e180-9dda-11eb-8419-68407a266f86.PNG">

The other figure cells display messages similar to this: 

`<AxesSubplot:title={'center':'10-min Global Solar Flux'}, xlabel='Year', ylabel='Irradiance (W/m2)'>
Text(0.5, 1.0, '10-min Global Solar Flux Histogram')
Text(0.5, 0, 'W/m2')
Text(0, 0.5, 'Count')`

python version 3.8.5
matplotlib version 3.3.4 
jupyterlab version 2.2.6

I would really appreciate your help solving this.

**Comment by martinRenou** [comment]
Any chance you could upgrade to JupyterLab 3? Installing all the latest versions from a clean environment should easily get you to a working setup.

**Comment by ianhi** [comment]
Maybe the readme should have a troubleshooting section that details how to create a working env. Something like:

```bash
conda create -n ipympl-test -c conda-forge jupyterlab ipympl
conda activate ipympl-test
```

**Comment by moira92** [comment]
> Any chance you could upgrade to JupyterLab 3? Installing all the latest versions from a clean environment should easily get you to a working setup.

I just updated to version 3.0.11 but it still doesn't work. I also updated the widget directly within the extension tab and then rebuilt everything. Any other suggestions of what I could do? I still get the "loading widget" message I mentioned previously. Perhaps I can uninstall the extension and install it again? Although I do not see the uninstall option in the extension tab, do you know the specific comand? can't find it. 

-----

> Maybe the readme should have a troubleshooting section that details how to create a working env. Something like:
> 
> ```shell
> conda create -n ipympl-test -c conda-forge jupyterlab ipympl
> conda activate ipympl-test
> ```

I'm not familiar with creating new environments. I write this on the terminal and then try running my notebook again? 

Thank you both for your help!

**Comment by ConyKitty** [comment]
Now it's works well in:
jupyterlab                3.1.4
matplotlib                3.1.0
Python                     3.7.6
Though no sure what caused, the bug maybe fixed so I closed the issue, thanks for all of your help.
