### ISSUE TITLE
Renaming repository to ipympl?

### ISSUE THREAD

**Issue by SylvainCorlay** [matplotlib/ipympl#192]
Would it make sense to rename the repository to match the name of the Python package (instead of the JS package)?

cc @martinRenou @tacaswell 

Note that links to the old repo URL would be redirected to the new one, should we rename the repository...

**Comment by tacaswell** [comment]
`jupyter-matplotlib` is a much better name, but I think the confusion of having two names is not worth it.

**Comment by thomasaarholt** [comment]
I think @tacaswell nailed it. +1.

**Comment by martinRenou** [comment]
I also prefer the `jupyter-matplotlib` name, even if it's longer. Maybe ipympl could be replaced by jupyter-matplotlib?

**Comment by thomasaarholt** [comment]
I think then it would have to be `jupyter_matplotlib`?

**Comment by SylvainCorlay** [comment]
Note: there is a pattern in the jupyter widgets name:

ipyleaflet  (python) -> jupyter-leaflet (js)
ipwebrtc (python) -> jupyter-webrtc (js)

I likr the current names of packages, but wondering about the repository name.

**Comment by SylvainCorlay** [comment]
This is done! Closing the issue.
