### ISSUE TITLE
Simpler installation for Jupyterlab?

### ISSUE THREAD

**Issue by BrenBarn** [matplotlib/ipympl#194]
As far as I can tell, the current procedure for getting plotting working in Jupyterlab involves installing four separate things, namely nodejs, two jupyterlab widgets, and jupyter-matplotlib itself.  This is a quite cumbersome mechanism.  Is there any possibility to create a more straightforward system whereby the end user can just install a single conda package and immediately have plots that work?

I've been teaching some classes over the past year using Jupyter.  Overall I think Jupyterlab has many advantages, but the increased complexity of matplotlib setup is an obstacle to fully shifting to Jupyterlab for beginners.  With classic notebook all you need to do (I think) is install matplotlib itself.  It would be nice if we could get to a somewhat similar point with Jupyterlab.

**Comment by martinRenou** [comment]
I just want to say that we are not ignoring your comment. I think we all agree with this, we would all benefit from making this simpler. I'll see if I can come up with something.

**Comment by maedoc** [comment]
Maybe this should be a separate issue, but falls in the "lab" bin:  I tried to set this up with JupyterLab in a container and JupyterLab simply doesn't load after installing ipympl.  My Dockerfile looks like this:
```dockerfile
FROM continuumio/miniconda3
RUN conda install -y jupyter
RUN conda install -c conda-forge jupyterlab
RUN conda install -y matplotlib

RUN conda install -c conda-forge ipympl \
 && conda install nodejs \
 && jupyter labextension install @jupyter-widgets/jupyterlab-manager \
 && jupyter labextension install jupyter-matplotlib

EXPOSE 8888

CMD jupyter lab --ip=0.0.0.0 --allow-root
```
Why does this fail?  Should it fail in Docker but not a "real" deployment?

**Comment by martinRenou** [comment]
This should work. 

Can you tell me:
- how it's failing?
- which version of JupyterLab do you have?
- which version of @jupyter-widgets/jupyterlab-manager do you have?
- which version of ipympl do you have?
- which version of jupyter-matplotlib do you have?

**Comment by maedoc** [comment]
It turns out to be a problem with MS Edge (I've Microsoft Edge 44.19041.1.0); opening in Firefox JupyterLab loads and I'm able to be make small plots.

**Comment by martinRenou** [comment]
Ok thanks! Does JupyterLab works in MS Edge without ipympl?

**Comment by maedoc** [comment]
> JupyterLab works in MS Edge without ipympl?

yes, that's actually why I didn't think to test on Firefox before my first comment.

**Comment by martinRenou** [comment]
Thanks for your feedback. I never tested on MS Edge.

Do you get an error message in the JavaScript console?

**Comment by jasongrout** [comment]
Note that JupyterLab does not officially support Edge: https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers

Perhaps that can be revisited now that Edge has matured quite a bit.

**Comment by jasongrout** [comment]
> Perhaps that can be revisited now that Edge has matured quite a bit.

And especially since Edge now uses the same underlying engine as Chrome.

**Comment by moorepants** [comment]
I just want to add my 2 cents. I'm a long time matplotlib & jupyter user and these jupyter lab extensions are really be difficult to get working. I just updated my primary conda environment which had this extension working and now it doesn't work. I've tried running all the extension commands to no avail. I agree with @BrenBarn that this is very problematic for student use, especially when the professor can't even get it working. I would love if `conda install ipympl` just worked. Why can't all the JS magic be packaged into a conda tarball? (or packaged in a pip tarball) That would be ideal. An example of this working is plotly and its associated tools. All the JS code is packaged up with the Python code for a complete working system.

**Comment by martinRenou** [comment]
I know it is painful and I would like things to be improved.

Since the latest version of ipympl. The JS tarball is also packaged when doing `conda install ipympl`. But this does not magically fix everything, because you still need to rebuild JupyterLab with `jupyter lab build`, or install the `@jupyter-widgets/jupyterlab-manager` extension if you did not do it.

But this whole JupyterLab extension system might be improved in the future.

**Comment by jasongrout** [comment]
FYI, overhauling the jlab extension system, and in particular how things will be packaged and distributed and installed, is a major goal for jlab 3.0: https://github.com/jupyterlab/jupyterlab/issues/8038

**Comment by henrypinkard** [comment]
I see that jlab 3.0 has been released, but as far as I can tell this is still an issue. Are there simpler instructions for setup now?

**Comment by jasongrout** [comment]
I just tested it. I installed with `pip install ipympl` in a clean environment and it just worked in jlab 3. So I think this is resolved now.

**Comment by jasongrout** [comment]
As noted in the readme, all you need to do for JupyterLab 3 is `conda install ipympl` or `pip install ipympl`.
