### ISSUE TITLE
a simple interactive matplotlib plot is not showed in jupyter lab

### ISSUE THREAD

**Issue by eurydice76** [matplotlib/ipympl#201]
Hello,

I try to plot interactively a simple plot through jupyterlab. Here is the code I use to do so:

```
%matplotlib widget
plt.figure()
x = [1,2,3]
y = [4,5,6]
plt.plot(x,y)
plt.show()
```

Unfortunately, running that code produces the following output:

`Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …
`

which seems to indicate that something is wrong with the rendering.
I followed the instructions for installing all the dependencies according other posts and documentation but it did not help. Here is what I installed:

```
conda install -c conda-forge ipympl
conda install -c conda-forge nodejs
conda install -c conda-forge widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
```
Here is some info about the versions of my different packages:

```
python: 3.6.7
ipympl: 0.5.3
jupyter-lab: 2.0.1
jupyterlab-extension: 2.0.1
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.0.0
jupyter lab      : 2.0.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```
would you have any idea ?

Many thanks in advance

**Comment by martinRenou** [comment]
You did not miss anything in the installation. 

Did you refresh the JupyterLab page?

**Comment by eurydice76** [comment]
yeap, I refreshed the page, logout from jupyterhub but still the same bad behaviour

**Comment by martinRenou** [comment]
Do you get an error in the JavaScript console? `ctrl + shift + J` on Chrome, `ctrl + shift + K` on Firefox

**Comment by eurydice76** [comment]
the only "Error" I can see is the following:

`Error: "Object 'jupyter.widget' not found in registry"`

**Comment by martinRenou** [comment]
Ok. Did you try rerunning `jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib`? There was a period of time when this did not work around last week.

**Comment by eurydice76** [comment]
I launched those commands just a few hours ago

**Comment by martinRenou** [comment]
Can you run `which jupyter` and show me the output?

**Comment by eurydice76** [comment]
here is what I get:

`/localhome/jhub-admin/conda/envs/test/bin/jupyter`

**Comment by martinRenou** [comment]
Thanks.

Now can you show me the output of:
```
ls /localhome/jhub-admin/conda/envs/test/share/jupyter/lab/extensions
```

**Comment by eurydice76** [comment]
Here I should give more informations. I use the conda kernel extension for isolating my kernel in diffferent conda environment. There is one conda env for jupyterhub and another in which the error occurs.

**Comment by eurydice76** [comment]
jupyter-matplotlib-0.7.2.tgz  jupyter-widgets-jupyterlab-manager-2.0.0.tgz

**Comment by martinRenou** [comment]
This seems right to me.

I am not familiar with the conda kernel extension.

Where are located your two conda environments?

**Comment by eurydice76** [comment]
/localhome/jhub-admin/conda/envs/test is the one with the bad behaviour

**Comment by martinRenou** [comment]
Did you try doing `jupyter lab build` in this one?

**Comment by eurydice76** [comment]
not yet. Let me try

**Comment by eurydice76** [comment]
still the same error

**Comment by martinRenou** [comment]
Does

```
from ipywidgets import IntSlider

IntSlider()
```

give you a slider?

**Comment by eurydice76** [comment]
No, it gives me:

`IntSlider(value=0)`

**Comment by martinRenou** [comment]
I don't know what to say.

Your ipywidgets installation seems to be broken in this environment. I would suggest nuking it, and reinstalling everything in a clean environment.

**Comment by eurydice76** [comment]
unfortunately, I did that tenth of times today but still with the same result. Anyway, thanks a lot for your help.

**Comment by martinRenou** [comment]
Sorry if I could not help more. Try to reach out on https://gitter.im/jupyter-widgets/Lobby. Someone might have an idea.

**Comment by eurydice76** [comment]
ok, thanks for the help and the hint

**Comment by fomightez** [comment]
Things seem in a bit of a flux at this moment. JupyterLab 2.0.1, which it appears you are using, only came out a week ago. As a work-around for now, I'd suggest you try changing the end of your URL from `lab` to `tree` and try running it in the classic notebook interface. You can demonstrate for yourself that it fixes the demo binder that they have in this repo by going to [here](https://github.com/matplotlib/ipympl), clicking `launch binder`, and trying to run the demo in JupyterLab first. Now when you edit the URL to switch interfaces, and try again, it works. (Granted, the demo does report different text output than you see; [elsewhere](https://mybinder.org/v2/gh/fomightez/communication_voila/master?filepath=scripts%2Fvoila_and_matplotlib.ipynb), where I do get the text output you report, the word-around works.)

**Comment by eurydice76** [comment]
Thanks for the info. I tried to switch to jupyter classic but it failed too. I will try to downgrade my jupyterlab and see what's going on. I keep you in touch.

**Comment by fomightez** [comment]
You can go [here](https://github.com/fomightez/bendit-binder) and see the work-around works in JupyterLab 2.0.1 installs, too. I didn’t link it before because you need to run `%pip install ipympl` in a notebook as well. Combined with the need to change the URL, I thought it best I not mention it. It may be though the Binder install has a little more supporting cruft for the classic interface than your install.

You were able to switch interfaces? It was just your plot didn’t work? 

By the way that ‘elsewhere’ link in my above post has a few more working ipyml examples.

**Comment by eurydice76** [comment]
I can switch between classic and lab interface, no problem on that side. The only problem is about plotting interactive plot. The `%matplotlib inline` magic is OK but not the `%matplotlib widget`.

My setup is the following and I must stock on it unfortunately: I have several conda environments (python2, python3, R, julia ...) around a master one which contains jupyter/jupyerlab/jupyterhub. All of this working through [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) . I am not sure to fully understand your recommendations. One question I still have is: should I install jupyterlab in each conda environment or just in the master one ? On my master node, here is my setup:
```

jupyterlab            : 0.35.6
jupyter core         : 4.6.1
jupyter-notebook : 6.0.1
qtconsole            :  not installed
ipython                : 7.11.1
ipykernel             : 5.1.3
jupyter client       : 5.3.4
jupyter lab           : 0.35.6
nbconvert            : 5.6.1
ipywidgets           : not installed
nbformat              : 5.0.3
traitlets                 : 4.3.3
```
what do you think ?

**Comment by fomightez** [comment]
I was just hoping the work-around that usually works for me, worked for you. I guess it doesn’t. 

You showed at the top the environment you are in has ipywidgets and ipympl. So things should work in classic interface at the very least. I don’t think installing JupyterLab in other conda environments is going to help. A new venv with all brand new installs would be a better use of effort at this point.

**Comment by eurydice76** [comment]
that what I ended up trying and it finally works. Here is my conda environment for my master environment:
```

name: test_new

channels:

  - conda-forge
  - defaults

dependencies:

  - notebook
  - jupyterlab
  - configurable-http-proxy
  - nb_conda
  - nb_conda_kernels
  - nodejs
  - widgetsnbextension
  - pip
```

Many thanks for your involvement and your help. Let's close the issue.
