### ISSUE TITLE
ipympl with Jupyterlab and IPython kernel in different virtual envs

### ISSUE THREAD

**Issue by m1nde** [matplotlib/ipympl#211]
Hello,
my situation looks like this: 
I have two different virtual environments (created with poetry, but I don't think this is the culprit).
* Venv 1 contains jupyterlab 1.2.8, jupytext, ipympl 0.5.6 and the jupyter-matplotlib 0.7.2 extension
* Venv 2 contains jupyterlab 1.2.8, ipympl 0.5.6, the jupyter-matplotlib 0.7.2 extension, and the rest of my dependencies

I installed venv 2 as an IPython kernel via the usual `ipython kernel install --name 'venv2' --user`.
Then I start JupyterLab in venv1 via `jupyter lab` and create a new notebook using jupytext. When I try to plot something in this notebook, the resulting plot is not rendered, but displayed as text `Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …`:
![screenshot](https://files.catbox.moe/vi0vqx.png)

I don't know if I am doing something wrong or this mode or splitting jupyter and the kernel into two virtual envs is not supported by ipympl. Can someone help me please?

**Comment by martinRenou** [comment]
Hello.

Do you have classical widgets working?
Do you get a slider if you do:
```python
from ipywidgets import IntSlider
display(IntSlider())
```

**Comment by m1nde** [comment]
Hello Martin, 
thank you for taking the time to help me with my issue. Running your code in a cell also produces only text output:
![screenshot](https://files.catbox.moe/qtedr7.png)

**Comment by martinRenou** [comment]
Ok.

Could you show me the output of `jupyter labextension list`

**Comment by m1nde** [comment]
Looking at the output of `jupyter labextension list` I noticed that `@jupyter-widgets/jupyterlab-manager` was disabled in venv1. I have no idea how that happened, I have been deleting, installing and reinstalling virtuals envs all day. I enabled the jupyterlab-manager extension now and the plots are correctly shown. Thanks a lot for guiding me in the right direction!

**Comment by m1nde** [comment]
Fixed by enabling `@jupyter-widgets/jupyterlab-manager` extension in the venv where jupyterlab is started.

**Comment by martinRenou** [comment]
Nice!
