### ISSUE TITLE
Compatibility information

### ISSUE THREAD

**Issue by Waateur** [matplotlib/ipympl#216]
I'm trying to make ipympl work with my jupyterlab installation. I'm almost certain that there is an issue with the version that I'm using  (see other issues like  #130 ). 
It's rather hard to find out which ipympl versions is supposed to go with which versions of jupyter-matplotlib and jupyterlab. 
May be there is a convention about this compatibility that I couldn't find. If it's not the case
i think we can use this issue to compile compatible version of ipympl and put that information inside the main README. 

I'll start with mine. The only version I'm able to make working is : 
- jupyterlab : 1.1.3 
- ipympl : 0.3.3
- jupyter-matplotlib : 0.4.2

**Comment by martinRenou** [comment]
A compatibility table is indeed a good idea. I made one for bqplot very recently https://github.com/bqplot/bqplot#install-a-previous-bqplot-version. We can make one for ipympl as well, it should not take too much time.

Although I would recommend always using latest.

That being said, I am trying my best to make life easier for users. Recently I added the JupyterLab extension as part of the package. Which means that if you install ipympl with conda you should get the JupyterLab extension with it automatically. Note that you still need to rebuild JupyterLab, and install the jupyter-widgets labextension if not done already.
```bash
conda install -c conda-forge ipympl

# Rebuild JupyterLab
jupyter lab build

# Or install the ipywidgets extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by Waateur** [comment]
Actually bqplot was the repository that inspired my request :) .

Is latest supposed to work with older jupyterlab version ?

I totally missed the "Or" .  I did the ``` labextension  install``` . Maybe that was the source of all my issues. 

I'm gonna check into  that. 
Thanks for the reply.

**Comment by martinRenou** [comment]
> Is latest supposed to work with older jupyterlab version ?

It *should*. Although I would highly recommend using the latest JupyterLab.

> I did the labextension install every times . Maybe that was the source of all my issues

Doing `labextension install` will do no harm if you have the latest ipympl with the latest JupyterLab. But I would not recommend doing it anymore just to be sure.
Did you find your issue?

I will make this table in the README. We want to document ipympl a bit more as well, there is another issue for that.

**Comment by martinRenou** [comment]
I opened a PR for the versions table, any comment from you would be very much appreciated :)
