### ISSUE TITLE
resize function is missing

### ISSUE THREAD

**Issue by Chang-Hsinyi** [matplotlib/ipympl#224]
Hi,

Does any have the same problem that resize function circled on the below pictures is missing?

<img width="862" alt="Screen Shot 2020-05-17 at 11 29 48 AM" src="https://user-images.githubusercontent.com/49727245/82135161-ecb00700-9831-11ea-9ef2-b2b49cb9fee8.png">

**Comment by martinRenou** [comment]
Which ipympl version do you have?

**Comment by Chang-Hsinyi** [comment]
it is 0.3.3   
By the way, I notice, in a python script, just one cell can have plot windows. That is to say, if A cell already has plot windows, then if I would like to show the plot in cell B, plot in cell A will miss.

**Comment by martinRenou** [comment]
Your ipympl version is not recent enough to have the resize button. Please try to update to the latest version so you have it.

**Comment by Chang-Hsinyi** [comment]
As I upgrade it, I got this error "Error displaying widget: model not found"

**Comment by martinRenou** [comment]
Do you use Jupyter Notebook or JupyterLab?

**Comment by Chang-Hsinyi** [comment]
Yes, I used jupyterlab.

pip list
ipympl                             0.5.6       
jupyter lab                       1.2.6
node js                             10.13.0

Below, is my extension,
<img width="504" alt="Screen Shot 2020-05-19 at 10 29 20 AM" src="https://user-images.githubusercontent.com/49727245/82277987-bd2d0600-99bb-11ea-9bdd-04440e7ffc8f.png">

**Comment by martinRenou** [comment]
This seems right, although I am not sure about the `@jupyter-widgets/jupyterlab-manager` extension, would you mind trying to reinstall it?

**Comment by Chang-Hsinyi** [comment]
Yes, I have tried to reinstall it!
I notice that it can work on jupyter notebook, while it will fail on jupyter lab.

**Comment by SylvainCorlay** [comment]
@Chang-Hsinyi it seems that you are using jupyterlab 1.x.

You need to install an older `@jupyter-widgets/jupyterlab-manager`.

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1
```

**Comment by Chang-Hsinyi** [comment]
After installing the @jupyter-widgets/jupyterlab-manager@1.1, I got this information below,

<img width="885" alt="Screen Shot 2020-05-23 at 4 03 53 PM" src="https://user-images.githubusercontent.com/49727245/82725375-1aec8580-9d0f-11ea-9cc1-2b9c3345d893.png">
