### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/ipympl#225]
It might be nice to have some sort of template for issues. 
Just to make people have to think about what their latest version is.
Something like the following, perhaps?

> In general, please make sure you are using the latest versions of software when reporting an issue.
> Please include the result of the following commands, which will print out the version of python, ipympl and the jupyter ecosystem.
> ```
> python -c "import sys; print(sys.version); import ipympl; print('ipympl version:', ipympl.__version__)" & jupyter --version
> ```
> \`\`\`
> Paste here.
> \`\`\`

This gives the following output:
```python
3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:32:17) [MSC v.1916 64 bit (AMD64)]
ipympl version: 0.5.6
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.2
ipython          : 7.13.0
ipykernel        : 5.2.0
jupyter client   : 6.1.3
jupyter lab      : 2.1.0
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```

**Comment by martinRenou** [comment]
Good idea, will do that

**Comment by martinRenou** [comment]
Please tell me what you think #226
