### ISSUE TITLE
Documentation: Flags to set notebook-wide default behavior

### ISSUE THREAD

**Issue by gsaurabhr** [matplotlib/ipympl#229]
This is a continuation of the enhancement fixed with #134 . The fix in #134 allows hiding the figure headers by setting a figure-specific flag:
```
f = plt.figure()
f.canvas.header_visible = False
```
A further enhancement would be to not have to do this for every figure, but set the default behavior via a global flag, for example, something similar to `mpl.rcParams` for ipympl. This could potentially be useful for other global behaviors of the package.

**Comment by martinRenou** [comment]
One thing I realized today is that you can actually do it, thanks to traitlets.

You can do:
```python
from ipympl.backend_nbagg import Canvas

Canvas.header_visible.default_value = False
```

**Comment by gsaurabhr** [comment]
Perfect, thank you, that works!

**Comment by martinRenou** [comment]
Sure :) Let's keep your issue opened until this is properly documented somewhere

**Comment by gsaurabhr** [comment]
Just wanted to link this to #208.

**Comment by martinRenou** [comment]
Thanks, this really need to be done. I'll try to take some time to do it at some point.

**Comment by mlt** [comment]
> You can do:
> ```python
> from ipympl.backend_nbagg import Canvas
> Canvas.header_visible.default_value = False
> ```
Any solution for JupyterLab as [nbagg does not work there](https://matplotlib.org/stable/users/explain/interactive.html#jupyter-notebooks-jupyterlab)?

**Comment by ianhi** [comment]
> Any solution for Jupyter Lab as [nbagg does not work there](https://matplotlib.org/stable/users/explain/interactive.html#jupyter-notebooks-jupyterlab)?

The quoted code will work in either jupyter lab or jupyter notebook. The name `backend_nbagg` is a relic of where the `ipympl` code came from

**Comment by mlt** [comment]
Nope...
![image](https://user-images.githubusercontent.com/413384/222059343-7bf7065b-4565-4099-a07f-c194de897420.png)
Do I drop it at the wrong place??

**Comment by ianhi** [comment]
huh - indeed that doesn't seem to work - I wonder if some update must've broken it along the way.

I suspect in this case that there is a conflict between the typescript defaults and the python defaults of these traits and somehow the typescript side is winning.

**Comment by s-bien** [comment]
Is the notebook-wide flag going to be fixed for Jupyter Lab?
