### ISSUE TITLE
incorrect version in lookup table

### ISSUE THREAD

**Issue by ianhi** [matplotlib/ipympl#247]
@martinRenou I think the version table is wrong:
![image](https://user-images.githubusercontent.com/10111092/87691890-2087aa00-c759-11ea-8203-ef0cf4798516.png)

because `0.5.7` python also requires the new changes on the js side.

**Comment by martinRenou** [comment]
Good catch! I went a bit fast updating this. Thanks for reporting.

**Comment by ianhi** [comment]
Is the ultimate solution to start matching the versions at some point? Just an aggressive bump to the python version in order to keep them in sync?

**Comment by martinRenou** [comment]
The JS and Python packages happen to be on the same repository, but I don't think it's a good reason for keeping both in sync. It might be out-of-sync again at some point anyway. Why do you think we should sync them?
