### ISSUE TITLE
"Loading widget..." & "Jupyter Lab: Error displaying widget: model not found"

### ISSUE THREAD

**Issue by leej11** [matplotlib/ipympl#259]
## Describe the issue

I've tried following the installation instructions but when trying to use `%matplotlib widget` I'm getting the 2 errors written in the title. The former occurs if my plot is in the same code cell as the `%matplotlib widget` magic command, the latter occurs when they are in separate code cells (at least thats what it seems to me).

The notebook cell code:
```python
%matplotlib widget
import matplotlib.pyplot as plt

plt.figure()
x = [1,2,3]
y = [4,7,8]
plt.scatter(x,y)
plt.show()

>>> Loading widget...
```

## Versions

```
 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)]
ipympl version: 0.3.3
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.1.5
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
Known nbextensions:
  config dir: C:\Users\Liam\miniconda3\envs\bournemouth_mapping\etc\jupyter\nbconfig
    notebook section
      jupyter-matplotlib/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
JupyterLab v2.1.5
Known labextensions:
   app dir: C:\Users\Liam\miniconda3\envs\bournemouth_mapping\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        jupyter-matplotlib v0.4.2 enabled  ok
```

**Comment by leej11** [comment]
Ahh, upgrading my version of `ipympl` worked! 

Strange though, when I initially installed it, I just ran `conda install ipympl` so not sure why it pulled down such an old version. Thanks for your help though!

**Comment by ianhi** [comment]
conda can be filled with mystery, I'd try using [mamba](https://github.com/TheSnakePit/mamba) instead of conda whenever possible. It is faster, and anecdotally I've run into fewer issues with weirdly old versions being installed.

**Comment by martinRenou** [comment]
Closing as fixed! Thanks @ianhi for helping :)
