### ISSUE TITLE
Double-click events are not recognised

### ISSUE THREAD

**Issue by ianhi** [matplotlib/ipympl#261]
Originally posted by @nvaytet in https://github.com/matplotlib/matplotlib/issues/18404

Posting here because ipympl will not automatically inherit whatever solution gets implemented for nbagg

> ### Bug report
> 
> **Bug summary**
> 
> Using the first example from the [events documentation](https://matplotlib.org/3.3.1/users/event_handling.html) detects double-click events properly in the Qt backend, but when used in a Jupyter notebook, the two clicks are recognised as two separate single click events.
> 
> **Code for reproduction**
> 
> I've adapted the code to show the contents of the `event` as the figure title instead of a `print` statement, because the output of `print` statements inside functions triggered by events disappear in Jupyter notebooks.
> 
> ```python
> import matplotlib.pyplot as plt
> import numpy as np
> fig, ax = plt.subplots()
> ax.plot(np.random.rand(10))
> 
> def onclick(event):
>     ax.set_title('%s click: button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
>           ('double' if event.dblclick else 'single', event.button,
>            event.x, event.y, event.xdata, event.ydata))
> 
> cid = fig.canvas.mpl_connect('button_press_event', onclick)
> ```
> 
> **Actual outcome**
> 
> The title always says `single-click`, no matter how fast I do my double-clicking.
> 
> ![Screenshot at 2020-09-04 08-02-20](https://user-images.githubusercontent.com/39047984/92204984-ffa02300-ee84-11ea-9f2d-c4a932cc91cc.png)
> 
> The double click events are properly captured when using the standard Qt window renderer.
> I have tried both the default `%matplotlib notebook` backend and the `ipympl` widget backend, and they show identical behaviour.
> 
> **Matplotlib version**
> 
>     * Operating system: Ubuntu 20.04
> 
>     * Matplotlib version: 3.2.2
> 
>     * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg, ipympl
> 
>     * Python version: 3.7.6
> 
>     * Jupyter version (if applicable): jupyter_client=6.1.6, jupyter_core=4.6.3, notebook=6.0.3
> 
>     * Other libraries:
> 
> 
> Installed in a `conda` env from `conda-forge`.

**Comment by nvaytet** [comment]
Is there any update on this? It has been fixed in nbagg for a while.
Thanks!

**Comment by ianhi** [comment]
Should be released as `0.9.0` now!
