### ISSUE TITLE
add tests via nbval

### ISSUE THREAD

**Issue by ianhi** [matplotlib/ipympl#265]
## Describe the issue

It would be great to have a test notebook that was run using [nbval](https://github.com/computationalmodelling/nbval) and tested against several version of matplotlib as well matplotlib master maybe? This could help pick up errors like https://github.com/matplotlib/ipympl/issues/252 more quickly.

**Comment by martinRenou** [comment]
I agree. We might not even need nbval, a simpler test set with pytest might be enough?

**Comment by ianhi** [comment]
Do methods such as `display` get properly tested by pytest?

**Comment by ianhi** [comment]
Also, if we use jupyterlab-browsercheck maybe we could notice the javascript errors that come from a broken install? I think we added that to ipycytoscape

**Comment by martinRenou** [comment]
> I think we added that to ipycytoscape

Oh did you? I am really interested in this!

**Comment by ianhi** [comment]
I'm not entirely sure that I added it correctly or that it would pick up every pathology. See dicussion about adding it here: https://github.com/QuantStack/ipycytoscape/pull/131

**Comment by ianhi** [comment]
If the browser check could be made to run a few cells of a notebook then it would be awesome.
