### ISSUE TITLE
ipympl-0.5.8  creating troubles with Jupyterlab-3.0.0rc1

### ISSUE THREAD

**Issue by stonebig** [matplotlib/ipympl#268]
using latest jupyterlab-3.0.0.rc, i do but:
- to get it OK for the standard Jupyter Notebook:
   . jupyter.exe  nbextension enable --py --sys-prefix ipympl 
- but then in in python-3.9.0rc2.amd64\share\jupyter\lab\extensions:
   . jupyter-matplotlib-0.7.4.tgz appears 
- and when launching Jupyter lab:
   . jupyterlab-3.0.0rc1 asks my to rebuild lab (which is uncorrect in jupyterlab-3)
   . even If I didn't do Jupyter labextension install jupyter-matplotlib

I'm lost in searching for a solution

![image](https://user-images.githubusercontent.com/4312421/94367202-69ef6080-00dd-11eb-81be-54c5ec58b486.png)

**Comment by thomasaarholt** [comment]
Would you mind clearly explaining the steps as to how you are installing ipympl?

**Comment by stonebig** [comment]
steps should be :
- pip install --pre jupyterlab  jupyterlab-widgets
- pip install  numpy matplotlib ipympl nbclassic jupyter notebook
- jupyter.exe nbextension enable --py --sys-prefix ipympl

**Comment by stonebig** [comment]
with:
````
Package             Version
------------------- ------------
argon2-cffi         20.2.0.dev0
async-generator     1.10
attrs               20.2.0
Babel               2.8.0
backcall            0.2.0
bleach              3.2.1
certifi             2020.6.20
cffi                1.14.3
chardet             3.0.4
colorama            0.4.3
cycler              0.10.0
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
idna                2.10
ipykernel           5.3.4
ipympl              0.5.8
ipython             7.18.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.1
Jinja2              2.11.2
json5               0.9.5
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.6.3
jupyter-server      1.0.1
jupyterlab          3.0.0rc1
jupyterlab-pygments 0.1.1
jupyterlab-server   2.0.0rc1
jupyterlab-widgets  1.0.0a2
kiwisolver          1.2.0
MarkupSafe          1.1.1
matplotlib          3.3.2
mistune             0.8.4
msvc-runtime        14.27.29016
nbclassic           0.2.1
nbclient            0.5.0
nbconvert           6.0.6
nbformat            5.0.7
nest-asyncio        1.4.0
notebook            6.1.4
numpy               1.19.2+mkl
packaging           20.4
pandocfilters       1.4.2
parso               0.7.0
pickleshare         0.7.5
Pillow              7.2.0
pip                 20.2.3
prometheus-client   0.7.1
prompt-toolkit      3.0.7
pycparser           2.20
Pygments            2.7.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pytz                2020.1
pywin32             228
pywinpty            0.5.7
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
requests            2.24.0
Send2Trash          1.5.0
setuptools          50.3.0
six                 1.15.0
sqlite-bro          0.9.1
terminado           0.9.1
testpath            0.4.4
tornado             6.0.4
traitlets           5.0.4
urllib3             1.25.10
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.35.1
widgetsnbextension  3.5.1
winpython           3.0.20200927

````

**Comment by martinRenou** [comment]
> and when launching Jupyter lab:
. jupyterlab-3.0.0rc1 asks my to rebuild lab (which is uncorrect in jupyterlab-3)
. even If I didn't do Jupyter labextension install jupyter-matplotlib

AFAIK this is correct in the current state of ipympl. We need to update ipympl for it to support the new JupyterLab extension system.

**Comment by jasongrout** [comment]
You can update to support the new extension system, but if time is tight, you can also just update package versions like previous jlab upgrades. The 1.x/2.x extension system is still available as well.

**Comment by martinRenou** [comment]
I'll try to take time this week for updating to the new extension system, thanks @jasongrout. Is this PR ready? https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/83 Can I use it as an example for the update?

**Comment by snickell** [comment]
Looks like this is still a relevant issue

@jasongrout do you have a sense what would be the best package versions to update to, or ideas where to look to find this?

**Comment by martinRenou** [comment]
I suppose the best approach for you would be to wait for JupyterLab 3 to be officially released. I made a PR updating ipympl for JupyterLab 3: https://github.com/matplotlib/ipympl/pull/272. I plan on merging it and releasing ipympl when JupyterLab 3 is out.

**Comment by snickell** [comment]
@martinRenou fyi, jupyterlab 3.0.0 is officially released on dec 23: https://www.npmjs.com/package/@jupyterlab/application

**Comment by snickell** [comment]
This is the same issue as #281 , which will probably attract more attention since it references the error most people will see as they upgrade to juplab 3, might be worth closing this one?
