### ISSUE TITLE
Blank interactive plot

### ISSUE THREAD

**Issue by jesse-eta** [matplotlib/ipympl#277]
## Describe the issue
I am running in Docker using Conda to setup the environment.

The following generates a blank plot from a notebook:

``` py
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
# Testing matplotlib interactions with a simple plot
fig = plt.figure()
plt.plot(np.sin(np.linspace(0, 20, 100)))
```

![image](https://user-images.githubusercontent.com/73847093/97902299-3dd58980-1cf2-11eb-81da-c26c23982587.png)

The following errors were seen via Chrome Developer Tools:
![image](https://user-images.githubusercontent.com/73847093/97902957-319dfc00-1cf3-11eb-8d6d-1410c0f321fa.png)

Making the plot without `%matplotlib widget` generates a plot with data:
![image](https://user-images.githubusercontent.com/73847093/97903509-ffd96500-1cf3-11eb-99f0-5c3d67ff672a.png)

## Versions

```
 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
ipympl version: 0.5.8
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 1.2.16
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
Config option `kernel_spec_manager_class` not recognized by `ListNBExtensionsApp`.
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      nbdime/index  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nb_conda/main  enabled 
      - Validating: OK
      nbpresent/js/nbpresent.min  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
JupyterLab v1.2.16
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @jupyterlab/celltags v0.2.0  enabled  OK
        @jupyterlab/git v0.11.0  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK
        plotlywidget v1.5.1  enabled  OK
```

Version of `matplotlib`:

``` bash
root@fa9b1a1a07fb:/# python -c "import sys; print('\n',sys.version); import matplotlib; print('matplotlib version:', matplotlib.__version__)"

 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
matplotlib version: 3.3.2
```

Version of `node`:
``` bash
root@fa9b1a1a07fb:/# node --version
v14.13.1
```

**Comment by ianhi** [comment]
Hey @jesse-eta are you able to upgrade to jupyterlab 2? Nominally ipympl works on jlab1 but there are far fewer people using it who would notice bugs. I'm also not sure if widgets will continued to be supported on jlab1 for much longer as jlab3 is about to come out (though they may well be - idk).

**Comment by jesse-eta** [comment]
Thanks for getting back so quickly. I am not sure that we can update to JupyterLab 2 because our notebooks are hosted by an external vendor but it seems like it is worth a shot.

It sounds like going down that path is a better bet than continuing to debug this issue with JupyterLab 1.
