### ISSUE TITLE
ipympl 0.6.1 does not produce figures in jupyter notebook

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/ipympl#287]
## Describe the issue

TLDR: No figure output in a fresh environment in Jupyter Notebook. It works in Jupyter Lab.

I created a new conda environment, installed and launched jupyter notebook:
```bash
conda create --name mpl jupyterlab ipympl matplotlib
conda activate mpl
# which jupyter -> /c/Users/thomasaar/Miniconda3/envs/mpl/Scripts/jupyter
jupyter notebook
```

I then called the following, and got no output (see screenshot below)
```python
%matplotlib widget
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2,3])
```

![image](https://user-images.githubusercontent.com/2721423/103640931-2ebcc300-4f51-11eb-9536-a8acc11cc77a.png)

Running the same notebook in Jupyter Lab works fine. This problem is only related to `jupyter notebook`.

## Versions

```
ipympl version: 0.6.1
jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : not installed
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 3.0.1
nbconvert        : 6.0.7
ipywidgets       : 7.6.2
nbformat         : 5.0.8
traitlets        : 5.0.5
Known nbextensions:
  config dir: C:\Users\thomasaar\Miniconda3\envs\mpl\etc\jupyter\nbconfig
    notebook section
      jupyter-matplotlib/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
JupyterLab v3.0.1
C:\Users\thomasaar\Miniconda3\envs\mpl\share\jupyter\labextensions
        jupyter-matplotlib v0.8.1 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)

```

**Comment by martinRenou** [comment]
Thanks a lot for reporting. Arf I've seen this issue once. I'll try to come up with a fix ASAP.

**Comment by thomasaarholt** [comment]
It's a pleasure reporting when one gets such responses :)

**Comment by martinRenou** [comment]
This is due to the Webpack update. There is the same issue in ipyleaflet.

**Comment by martinRenou** [comment]
Releasing this tonight.

**Comment by martinRenou** [comment]
@thomasaarholt You should be able to have it working with ipympl 0.6.2 (not yet on conda-forge)

**Comment by thomasaarholt** [comment]
Sweet, thanks!
