### ISSUE TITLE
remark: ipympl-0.6.2 seems to have no interactive feature working when under vscode-python

### ISSUE THREAD

**Issue by stonebig** [matplotlib/ipympl#295]
playing on latest Jupyter, with lates ipymml, with VScode-Python of today (new version next week):
- ipympl does render,
- but interactvity seems not working.

code tried:
````
%matplotlib widget
# Testing matplotlib interactions with a simple plot
import matplotlib.pyplot as plt
import numpy as np
# warning ; you  need to launch a second time %matplotlib widget, if after a %matplotlib inline 
%matplotlib widget

fig = plt.figure()  #plt.figure(1)
plt.plot(np.sin(np.linspace(0, 30, 100)))
plt.show()
````

![image](https://user-images.githubusercontent.com/4312421/104847089-5bbc8e80-58de-11eb-9f5d-b9cba9c3d460.png)

**Comment by ianhi** [comment]
Do other jlab3 compatible widgets work in vscode? For exmample does a slider from ipywidgets 7.6 work?

**Comment by asteppke** [comment]
An update to this issue: with the current ipympl (0..8.4) and Visual Studio Code 1.63.2 the widget and interactivity work well. 

What is still missing is that the png representation is not shown if the notebook is saved and reload in VS code which works in Jupyterlab.

**Comment by martinRenou** [comment]
Thank you for the update!

> What is still missing is that the png representation is not shown if the notebook is saved and reload in VS code

Is there something showed or is the cell output empty? I guess it's an issue on the side of VSCode, we won't be able to do much about it.

**Comment by asteppke** [comment]
Upon closer inspection VS code shows a tiny icon on the left: 
![image](https://user-images.githubusercontent.com/5851636/148043829-b62de727-e324-463e-a94f-f040640f353b.png)

This allows you to change the mimetype interpretation for this cell, and, when selecting mimetype as `image/png` the plot shows up correctly. So this now only requires a tiny change on the VS code people to show the `image/png` as a default if the `application/vnd.jupyter.widget-view+json` does not render any output. 

This has in general come so far and is is fantastic to see all these bits coming together.

**Comment by martinRenou** [comment]
Great :)

>  this now only requires a tiny change on the VS code people to show the image/png as a default if the application/vnd.jupyter.widget-view+json does not render any output

I guess it could be worth an issue/question in https://github.com/microsoft/vscode-jupyter.

I am surprised the `application/vnd.jupyter.widget-view+json` is not able to show up, I would expect the latest release to contain the static plot at least if there is no live kernel. Are other kinds of widgets like `ipywidgets.IntSlider` able to render when doing the save then reload?

**Comment by asteppke** [comment]
Yes, let's raise an issue there for the vscode people to address this. 

Regarding the other widgets, the `IntSlider` works in general, when reloading an `IntSlider` I get another icon at the side but no rendered output:
![image](https://user-images.githubusercontent.com/5851636/148045809-deb2b57c-0e08-4d7e-91b1-e390b2574d44.png)

When using that icon to change the mimetype to `text/plain` it yields something useful though as a text representation: `IntSlider(value=0)`

**Comment by martinRenou** [comment]
Ok, so I suppose it could be a general issue of vscode-jupyter not able to render any `application/vnd.jupyter.widget-view+json` on reload.

Please put a link here if you open a related issue on the vscode-jupyter repo :)

I will close this one as resolved.

**Comment by asteppke** [comment]
Great, let's see what the vscode-jupyter people can do about this. I created an issue at https://github.com/microsoft/vscode-jupyter/issues/8635.

**Comment by martinRenou** [comment]
Thanks!
