### ISSUE TITLE
Widget only shows on first view

### ISSUE THREAD

**Issue by bdch1234** [matplotlib/ipympl#307]
When creating a named figure, it is usually either because I need to display it elsewhere as well, or because I do repeated iterations of same plot to find a good set of parameters for it. But showing the plot again after it has been created does not show the toolbar, resizing-handle, or figure name, it is just the figure. A workaround for the latter case is to manually close the figure and recreate in each iteration, but that obviously does not work in the first case. An example is given below.

First view:
![figure1](https://user-images.githubusercontent.com/46796385/110025746-150ce180-7d30-11eb-8370-2cc438cb187e.png)
Second view:
![figure2](https://user-images.githubusercontent.com/46796385/110025768-1d651c80-7d30-11eb-8b24-25b96cb7062e.png)

**Comment by thomasaarholt** [comment]
I'm not entirely sure why this choice has been made. Maybe to preserve otherwise expected behaviour?
`plt.figure('test figure').canvas` (or `fig.canvas`, if you'd returned the first object as `fig`) includes the toolbar with the figure.

**Comment by bdch1234** [comment]
Got it. Thanks @thomasaarholt.
