### ISSUE TITLE
Zoom doesn't work in 3d plots

### ISSUE THREAD

**Issue by trbedwards** [matplotlib/ipympl#308]
## Describe the issue

I cannot use the rectangle zoom function to zoom in on 3d plots (see https://matplotlib.org/stable/gallery/mplot3d/surface3d.html for an example). Clicking on the rectangle zoom button and then clicking on the plot will just trigger a rotation.

## Versions

```
 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0]
ipympl version: 0.5.8
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.2
jupyter client   : 6.1.6
jupyter lab      : 2.1.5
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
Known nbextensions:
  config dir: /home/tedwards/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
JupyterLab v2.1.5
Known labextensions:
   app dir: /home/tedwards/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK```

**Comment by ianhi** [comment]
Hi @trbedwards thanks for the report.

I think this may actually be an issue in core matplotlib rather than ipympl - at least I can replicate the behavior in the pyqt backend. Can you try running the example not in a notebook and see if you get the same behavior?

**Comment by ianhi** [comment]
Ahh in fact it is this issue on core matplotlib: https://github.com/matplotlib/matplotlib/issues/110

**Comment by martinRenou** [comment]
Thanks @ianhi. Closing this issue then.
