### ISSUE TITLE
Jupyter -- Error displaying widget: model not found

### ISSUE THREAD

**Issue by lilacbeauty** [matplotlib/ipympl#329]
## Describe the issue
Testing the example ipynb script, got this error. such as:

# Testing matplotlib interactions with a simple plot
fig = plt.figure()
plt.plot(np.sin(np.linspace(0, 20, 100)));

Error displaying widget: model not found 

## Tried all those solutions I can found:
1. Testing widget with codes as follow, it shows slider.
from ipywidgets import IntSlider
IntSlider()

2. Tried command as follow, not worked.
sudo jupyter labextension update --all
sudo jupyter lab build minimum

3. Tried reinstall ipympl, not worked.

It's just not support JupyterLab 3 yet? ~~~~~~~~~~>_<~~~~~~~~~~~

## Versions
 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
ipympl version: 0.7.0
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.4.0
ipykernel        : 5.1.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 5.6.1
ipywidgets       : 7.6.3
nbformat         : 5.0.3
traitlets        : 5.0.0.dev
Known nbextensions:
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
JupyterLab v3.0.16
/usr/local/share/jupyter/labextensions
        jupyter-matplotlib v0.9.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /usr/local/share/jupyter/lab
        jupyter_clickable_image_widget v0.1.0 enabled OK*

   local extensions:
        jupyter_clickable_image_widget: /home/jetbot/Downloads/jupyter_clickable_image_widget-master/js

**Comment by martinRenou** [comment]
You seem to be using the extension "jupyter_clickable_image_widget", is it this one? https://github.com/jaybdub/jupyter_clickable_image_widget

If that's the case, then this is the culprit. It does not support JupyterLab 3 and breaks ipywidgets and ipympl.

**Comment by martinRenou** [comment]
Closing as answered, feel free to ask for more help
