### ISSUE TITLE
The example notebook does not work on Google Colab

### ISSUE THREAD

**Issue by miohtama** [matplotlib/ipympl#336]
## Describe the issue

The example notebook fails on Google Colab

1. Click https://colab.research.google.com/github/matplotlib/ipympl/blob/master/examples/ipympl.ipynb
2. Add and run `!pip install ipympl`
2. Click Runtime > Restart and run all

## Versions

```
 ipympl in /usr/local/lib/python3.7/dist-packages (0.7.0)
```

The `ipympl` fails in the section of `Interactions with other widgets and layouting`.

```
---------------------------------------------------------------------------

TraitError                                Traceback (most recent call last)

<ipython-input-13-4a044b406030> in <module>()
     13     center=fig.canvas,
     14     footer=widgets.Button(icon='check'),
---> 15     pane_heights=[0, 6, 1]
     16 )

9 frames

/usr/local/lib/python3.7/dist-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    688                     e = "The '%s' trait expected %s, not %s." % (
    689                         self.name, self.info(), describe("the", value))
--> 690                 raise TraitError(e)
    691 
    692     def get_metadata(self, key, default=None):

TraitError: The 'center' trait of an AppLayout instance expected a Widget or None, not the FigureCanvasAgg at '0x7f0ec0de9750'.
```

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/49922/126815072-3ed8ffcd-0460-4746-9fb5-22b0a1b986ba.png">

**Comment by martinRenou** [comment]
Yep. Unfortunately ipywidgets is supported in colab but not sub-widgets-packages like ipympl.

**Comment by martinRenou** [comment]
ipympl now works in colab!

**Comment by thomasaarholt** [comment]
@martinRenou I think it no longer works? Running `!pip install ipympl` at the beginning of this notebook and then restarting the kernel does not yield an interactive figure after running the `plt.figure()` cell.

https://colab.research.google.com/github/matplotlib/ipympl/blob/master/examples/ipympl.ipynb#scrollTo=rIZyNlcKJJ1k

**Comment by martinRenou** [comment]
You need to run the following for it to work:

```python
from google.colab import output
output.enable_custom_widget_manager()
```

**Comment by thomasaarholt** [comment]
Ah! Thansk!

**Comment by shaunc** [comment]
I'm getting this same error in a notebook in vscode. Is there a known workaround?
