### ISSUE TITLE
Having text outside of the viewport area makes the static repr of the figure go wrong

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/ipympl#340]
## Describe the issue

In a notebook:
```Py
import numpy as np
import matplotlib.pyplot as plt

%matplotlib widget

x = np.arange(10.)
y = np.random.random(10)
fig, ax = plt.subplots()
ax.plot(x, y)
ax.text(50, 5, "Hello")
ax.set_xlim(0, 11)
ax.set_ylim(0, 1)
```
shows the plot correctly, where the text is not visible in the viewport area.
![Screenshot at 2021-08-17 17-41-06](https://user-images.githubusercontent.com/39047984/129757982-227813d9-bd12-4989-8e2c-9728017396e9.png)

However, if I try to look at the static `__repr__` of the `fig` object (not the interactive `fig.canvas`), the text is caught in the bounding box and the resulting figure is tiny, with the text haging in the top right corner:
![Screenshot at 2021-08-17 17-41-20](https://user-images.githubusercontent.com/39047984/129758000-26d1bcb1-d88e-4aba-bcec-dc9766ec6997.png)

## Versions

```
 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]
ipympl version: 0.7.0
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.23.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
Known nbextensions:
  config dir: /home/nvaytet/software/miniconda3/envs/mantid/etc/jupyter/nbconfig
    notebook section
      jupyter-datawidgets/extension  enabled 
      - Validating: OK
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      jupyter-threejs/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by ianhi** [comment]
This is due to how `ipython` displays matplotlib figures. In particular in this funciton:
https://github.com/ipython/ipython/blob/322f2fe50d9dccb6134d3d61df7d90772ecf2751/IPython/core/pylabtools.py#L99-L125

they use `bbox_inches='tight'` which results in that behavior. You can see this by calling `plt.savefig('name.png', bbox_inches='tight')`

which is to say that I don't think that this is something ipympl can fix

**Comment by ianhi** [comment]
I think you probably can change the ipython settings to change the kwargs it uses which is a workaround, but I doubt that that the default will change

**Comment by nvaytet** [comment]
I see, I get the same result with the `inline` backend.
I will close then, thanks for the clarification.
