### ISSUE TITLE
Use precommit.ci?

### ISSUE THREAD

**Issue by ianhi** [matplotlib/ipympl#360]
I've been really enjoying using https://pre-commit.ci/ to have a bot automatically push style changes to PRs so that I never have to think about them again.

I would recommend a config file more or less looking like this: https://github.com/ianhi/pyrepo-cookiecutter/blob/ian/%7B%7Bcookiecutter.project_name%7D%7D/.pre-commit-config.yaml

I guess @martinRenou and @tacaswell ?

**Comment by martinRenou** [comment]
👍🏽 👍🏽  I would personally prefer this over a git hook solution,

**Comment by tacaswell** [comment]
👍🏻 I think both @ianhi and @martinRenou have enough GH permissions to ipympl to enable this.

**Comment by ianhi** [comment]
It seems I only had the power to request access, which I have now done. I have no idea who that requests access from or how they may or may not be notified.
