### ISSUE TITLE
New static repr of matplotlib plots saved at low-res

### ISSUE THREAD

**Issue by jklymak** [matplotlib/ipympl#361]
## Describe the issue
https://github.com/matplotlib/ipympl/pull/343 introduced static representation of matplotlib plots, which works great.  Except the png is low res, whereas it would probably be nicer at highres, at least for those with hiDPI screens:

### while widget Active
<img width="210" alt="Active" src="https://user-images.githubusercontent.com/1562854/134476879-dd422a82-4594-4ad4-b237-ad154529ba35.png">

### static repr of plot:

<img width="203" alt="Static" src="https://user-images.githubusercontent.com/1562854/134476948-67a28834-4039-432f-865b-8a47c4727cdf.png">

## Versions

...master

**Comment by ianhi** [comment]
Removed code is here: https://github.com/matplotlib/ipympl/pull/343#discussion_r714170820 I think restoring that will go a long way.
