### ISSUE TITLE
Debounce/throttle mouse events

### ISSUE THREAD

**Issue by martinRenou** [matplotlib/ipympl#385]
We should probably debounce or throttle most of the mouse events (pan, zoom etc) in order to improve performances

**Comment by asteppke** [comment]
Without throttling a bad user experience can be triggered if the backend requires _x_ milliseconds to generate a new plot but the mouse events are arriving every _y_ milliseconds with _y_ < _x_.  So this feature would help especially with complex plots.

At the moment without this one can stumble into almost unusable pan and zoom behavior. To keep a smooth & fast feeling it might be an idea to calculate on the frontend side how long the backend required to render (_x_ milliseconds) and then make sure that the throttling always sends update requests that are not faster than, e.g. _y_ =1.25 * _x_. This would prevent that requests pile up and the interface becomes very sluggish.

**Comment by martinRenou** [comment]
I guess it's difficult to compute the time it takes for the back-end to process a zoom/pan from the front-end, as the front-end doesn't know if the messages it receives are in response of the zoom/pan or something else.

I am making it configurable for now.

```
fig.canvas.pan_zoom_throttle = 300  # Throttling of 300ms
```
