### ISSUE TITLE
"ipympl" module can't be found in JupyterLab Desktop application

### ISSUE THREAD

**Issue by PkRPintu** [matplotlib/ipympl#388]
First of all, thanks for creating the "ipympl" module. I have been using it extensively in JupyterLab. However, with the recent launch of the standalone JupyterLab Desktop application, I wanted to switch from the web-based JupyterLab to JupyterLab Desktop.

However, in the JupyterLab Desktop application, I can't import the "ipympl" module. (ModuleNotFoundError: No module named 'ipympl')

Could anyone please let me know how it can be done?

Thanks a lot.

Cheers
Pradeep

https://github.com/jupyterlab/jupyterlab-desktop

**Comment by ianhi** [comment]
I think this is because jupyterlab desktop has it's own environment. See https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#Customizing-the-Bundled-Python-Environment

Can you try running `!pip install ipympl` from within a notebook?

**Comment by ianhi** [comment]
I opened a PR on jlab-desktop adding ipympl to the default environment we'll see where that goes.

**Comment by PkRPintu** [comment]
Dear ianhi,

Thanks a lot. !pip install ipympl does the job.

Best wishes
Pradeep

**Comment by ekesawi** [comment]
I have the same issue now where despite the fact that ipympl was installed via pip within juypterlab and yet i am getting the same error, "No module named 'ipympl". The strange thing is that i have exactly the same setting in my home computer which works well. I tried soem of the suggestions here, but none works.
