### ISSUE TITLE
Duplicate plot in a Jupyter notebook cell

### ISSUE THREAD

**Issue by Davide-sd** [matplotlib/ipympl#402]
## Describe the issue

To reproduce the problem, the following code block must be run into a Jupyter notebook or Jupyter lab cell:

```python
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np

class Test:
    def __init__(self):
        self._fig = plt.figure()
        self.ax = self._fig.add_subplot(1, 1, 1)

    def show(self):
        x = np.linspace(0, 10, 100)
        y = np.sin(x)
        self.ax.plot(x, y)
        self._fig.tight_layout()
        self._fig.show()

t = Test()
t.show()
``` 

The plot will be shown twice in the output cell. Note that if I revert back to ipympl v0.7.0, the same code block produces the correct output: only one plot.

## Versions

```
3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
ipympl version: 0.8.2
Selected Jupyter core packages...
IPython          : 7.30.1
ipykernel        : 5.5.5
ipywidgets       : 7.6.5
jupyter_client   : 7.1.0
jupyter_core     : 4.9.1
jupyter_server   : 1.12.1
jupyterlab       : 3.2.4
nbclient         : not installed
nbconvert        : 5.6.1
nbformat         : 5.1.3
notebook         : 5.7.11
qtconsole        : not installed
traitlets        : 5.1.1
```

**Comment by Davide-sd** [comment]
Interestingly, if I run `plt.ioff()` before executing the code block, only one plot will be shown!

**Comment by martinRenou** [comment]
The behavior of ipympl has changed to something closer to the inline backend. Turning off the interactive mode is indeed the way to go for you :)

**Comment by Davide-sd** [comment]
I wonder what trigger that behavior. For example, Sympy's plot functions (which uses a similar pattern illustrated above), do not trigger that behavior: I've checked the source code and interactivity is never turned off...

**Comment by Davide-sd** [comment]
I'm closing this issue.

The problem is that I used `self._fig.show()`, whereas I should have used `plt.show()`.
