### ISSUE TITLE
Replace the ipykernel dependency with an IPython dependency?

### ISSUE THREAD

**Issue by martinRenou** [matplotlib/ipympl#409]
## Describe the issue

In the `setup.py` file and in the conda-forge recipe, there is an ipykernel dependency that we could maybe get rid of. We should probably reduce the dependency to an IPython dependency, which we use directly in the codebase.

**Comment by martinRenou** [comment]
The conda-forge bot is complaining about the following:

```
Missing dependencies:
- traitlets
- jupyter-packaging
- numpy
- ipython
- pillow
- ipython_genutils

Unused dependencies:
- six
- ipykernel
```

**Comment by stonebig** [comment]
is it still mandatory to have the contraint ipython<8 ?
