### ISSUE TITLE
v0.9.0 breaks Output rendering in voila

### ISSUE THREAD

**Issue by marcelmindemann** [matplotlib/ipympl#463]
## Describe the issue

Using an `ipywidgets.Output` to capture some ipympl plots, then displaying the Output in Voila shows only "Loading Widget...". Works with ipympl 0.8.8.

Minimal code example:

```python
import matplotlib.pyplot as plt
import ipywidgets as widgets

%matplotlib widget
o = widgets.Output()

with o:
    plt.plot([1, 2, 3, 4])
    plt.ylabel('some numbers')
    plt.show()
    
o
```

Works in JupyterLab 3.3.0:
<img width="1035" alt="Screen Shot 2022-04-21 at 15 50 33" src="https://user-images.githubusercontent.com/12549786/164474422-ba5e5782-a479-4da7-aeaf-38600e98c070.png">

Does not work in voila + ipympl 0.9.0:
<img width="439" alt="Screen Shot 2022-04-21 at 15 50 39" src="https://user-images.githubusercontent.com/12549786/164474468-0fad6bb9-e98b-4bf9-b39c-381992321131.png">

Works in voila + ipympl 0.8.8:
<img width="901" alt="Screen Shot 2022-04-21 at 15 51 33" src="https://user-images.githubusercontent.com/12549786/164474502-e31e3484-d0f9-49eb-a764-30549e38f9c2.png">

## Versions

```
 3.9.10 (main, Feb  2 2022, 16:22:02) 
[Clang 13.0.0 (clang-1300.0.29.30)]
ipympl version: 0.8.8

Selected Jupyter core packages...
IPython          : 8.2.0
ipykernel        : 6.13.0
ipywidgets       : 7.7.0
jupyter_client   : 7.2.2
jupyter_core     : 4.10.0
jupyter_server   : 1.16.0
jupyterlab       : 3.3.4
nbclient         : 0.5.13
nbconvert        : 6.5.0
nbformat         : 5.3.0
notebook         : 6.4.11
qtconsole        : not installed
traitlets        : 5.1.1
Known nbextensions:
  config dir: /Users/marcel.mindemann/moia-dev/pooling-analytics/passt/discovery-panel/.venv/etc/jupyter/nbconfig
    notebook section
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      jupyterlab-plotly/extension  enabled 
      - Validating: OK
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
JupyterLab v3.3.4
/Users/marcel.mindemann/moia-dev/pooling-analytics/passt/discovery-panel/.venv/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyter-matplotlib v0.10.5 enabled OK
        jupyter-leaflet v0.16.0 enabled OK
        jupyterlab-plotly v5.7.0 enabled OK
        @pyviz/jupyterlab_pyviz v2.2.0 enabled OK (python, pyviz_comms)
        @voila-dashboards/jupyterlab-preview v2.1.5 enabled OK (python, voila)
        @jupyter-widgets/jupyterlab-sidecar v0.6.1 enabled OK (python, sidecar)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)
```

**Comment by martinRenou** [comment]
Can you try uninstalling ipympl, then removing the `/Users/marcel.mindemann/moia-dev/pooling-analytics/passt/discovery-panel/.venv/share/jupyter/labextensions/jupyter-matplotlib` directory entirely and install `ipympl v0.9.0` again?

Starting from this release, updating ipympl should be less painful.

**Comment by martinRenou** [comment]
Apparently there is the same issue with nbpshinx (which uses the ipywidgets HTMLManager) https://github.com/matplotlib/ipympl/issues/462

You can see in this issue's screenshots the same thing:
```
Falling back to https://cdn.jsdelivr.net/npm/ for jupyter-matplotlib@1.0.0
```

**Comment by martinRenou** [comment]
ipywidgets seems to be making a special case for ipywidgets...

https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/html-manager/src/htmlmanager.ts#L115-L123

**Comment by martinRenou** [comment]
I guess our only solution is to revert https://github.com/matplotlib/ipympl/pull/448 :( I am so sorry

**Comment by martinRenou** [comment]
It looks like if we want to implement #448 properly we need to update ipywidgets first

**Comment by DonJayamanne** [comment]
similar problem in vscode as well https://github.com/microsoft/vscode-jupyter/issues/9697
@martinRenou let me know if there's anything we need to do to get this fixed in vscode extension. thanks.

**Comment by martinRenou** [comment]
0.9.1 should fix this issue. I will mark the 0.9.0 release as broken on `conda-forge`.

@ianhi I reverted your changes on the widget versioning, again I am sorry for this. Though I've loosen a bit the back-end/front-end relationship by requiring `^0.11` instead of `^0.11.1`, see https://github.com/matplotlib/ipympl/blob/main/ipympl/_version.py#L3.
