### ISSUE TITLE
Transparent background by default in VSCode

### ISSUE THREAD

**Issue by MathieuMoalic** [matplotlib/ipympl#487]
By default, every widget in VScode (code-server in my particular case) will have a white background:
![image](https://user-images.githubusercontent.com/21007252/189622468-4f73ac76-5f08-4fae-b219-3e42fe1a9ebd.png)

jupyter lab works well though:
![image](https://user-images.githubusercontent.com/21007252/189623081-e8eef539-851e-45e7-be42-f18f2421be04.png)

This option in VSCode doesn't do anything whatsoever:
![image](https://user-images.githubusercontent.com/21007252/189623585-f90e4794-d62c-487f-b517-33bedceabcbc.png)

There is one (very ugly) workaround, running this in every single notebook:
```html
%%html
    <style>
    .cell-output-ipywidget-background {
       background-color: transparent !important;
    }
    .jp-OutputArea-output {
       background-color: transparent;
    }  
    </style>
```
Is there anything you can do about this or does it only depend on VSCode ? 

## Versions
code-server==4.7.0 7f108c61ab670ccaae4cfde5de2909c003db1ce8 with Code 1.71.0

ipywidgets==7.7.1

**Comment by martinRenou** [comment]
I'm tempted to say it's an issue with vscode-jupyter. It should probably be reported there https://github.com/microsoft/vscode-jupyter

**Comment by MathieuMoalic** [comment]
I understand. I was hoping you had solution because it looks like it won't be fixed from VSCode [any time soon](https://github.com/microsoft/vscode-jupyter/issues/7161).

**Comment by martinRenou** [comment]
Let's close this issue and continue here https://github.com/microsoft/vscode-jupyter/issues/7161
