### ISSUE TITLE
release failed

### ISSUE THREAD

**Issue by ianhi** [matplotlib/ipympl#518]
looks like the `0.9.3` release didn't actually make it through

https://github.com/matplotlib/ipympl/actions/runs/4186860606
I think we need
```
with:
   environment-file: false
```

we should add some words to the RELEASE.md for what to do in this case

**Comment by tacaswell** [comment]
well, on the bright side this means re-doing it will be picked up by zenodo!

**Comment by ianhi** [comment]
fixed the micromamba errors with: https://github.com/matplotlib/ipympl/commit/a39a31cc7c0799f6d8c83f82a12a9a09a6670e0d and have changes to the release doc

**Comment by ianhi** [comment]
npm failed: https://github.com/matplotlib/ipympl/issues/458

but I manually released that

**Comment by ianhi** [comment]
@martinRenou have you been manually updating the conda-forge on releases? Seems that way from: https://github.com/conda-forge/ipympl-feedstock/pulls?q=is%3Apr+is%3Aclosed

is there anything we need to do to make the magic bot make the PRs?

**Comment by martinRenou** [comment]
Thanks for fixing the action for releases!

> have you been manually updating the conda-forge on releases?

Yes I sometimes do manual releases if I don't want to wait for the bot. We don't have to do anything for the bot to make PRs https://github.com/conda-forge/ipympl-feedstock/pull/65, we just need to wait a bit.

**Comment by stevejpurves** [comment]
seems like `0.9.3` is now out and this can be closed?

**Comment by martinRenou** [comment]
Thanks!
