### ISSUE TITLE
JupyterLab 4.x support

### ISSUE THREAD

**Issue by mlhenderson** [matplotlib/ipympl#532]
Are there plans to migrate the ipympl extension to work in JupyterLab 4?  Trying to find out if anyone is currently working on this and any sort of anticipated timescale before it would happen.

**Comment by martinRenou** [comment]
I'm surprised it does not work as is. Do you see an error when using it in jupyterlab 4?

**Comment by martinRenou** [comment]
I just tried, it seems to work nicely in both JupyterLab 4 and Notebook v7

![Screenshot from 2023-07-27 09-18-12](https://github.com/matplotlib/ipympl/assets/21197331/4a6a5d68-a1d9-422a-bae7-063b9ffc0b98)


![Screenshot from 2023-07-27 09-19-34](https://github.com/matplotlib/ipympl/assets/21197331/5c6db506-46fa-4b69-8676-3175a0f980af)

**Comment by Photonnnn** [comment]
I find it that ```%matplotlib nbagg``` seems not to work with notebook 4 as I'm always getting error 'IPython is not defined'. When I switch to notebook 3 without changing any other environment (What I've done is just ```pip3 install --upgrade notebook==3```) my code works properly. I'm running https://github.com/microsoft/AI-For-Beginners/blob/main/lessons/3-NeuralNetworks/04-OwnFramework/OwnFramework.ipynb, I need nbagg to show the dynamic figure so in this case widget seems not to be a good choice.

**Comment by ianthomas23** [comment]
`%matplotlib nbagg` and `%matplotlib notebook` (they are the same thing) work with `jupyter notebook < 7` and `jupyter nbclassic`.
`%matplotlib ipympl` and `%matplotlib widget` (they are the same thing) work with `jupyter notebook >= 7` and `jupyter lab`
