### ISSUE TITLE
Latest version of everything still causes the dreaded Error displaying widget: model not found

### ISSUE THREAD

**Issue by davide-q** [matplotlib/ipympl#534]
## Describe the issue

![image](https://github.com/matplotlib/ipympl/assets/106841869/6e42ed96-10fb-41a8-852a-c6364bd56f96)

`<rant>`
Wouldn't it be possible to provide a more meaningful error message that does not end up fooling google and providing outdated solutions of many, many versions ago?
`</rant>`

## Versions

```

 3.11.2 (main, Jul 28 2023, 17:26:47) [GCC 13.1.0]
ipympl version: 0.9.3
Selected Jupyter core packages...
IPython          : 8.15.0
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.3.1
jupyter_core     : 5.3.1
jupyter_server   : 2.7.3
jupyterlab       : 4.0.6
nbclient         : 0.8.0
nbconvert        : 7.8.0
nbformat         : 5.9.2
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.10.0
JupyterLab v4.0.6
~/venvs/generic_python-3.11.2/share/jupyter/labextensions
        jupyter-matplotlib v0.11.3 enabled OK
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments

   Consider checking if an update is available for these packages.

```

**Comment by davide-q** [comment]
PS: works fine in the traditional notebook interface, i.e. changing the URL from `before/lab/tree/after` to `before/tree/after`

**Comment by JTem** [comment]
Hi, 

i had the same issue, i updated everything to the latest version, did same issue. 

i closed jupyterLab and restarted the pc and then it worked as expected. maybe that might help you too

**Comment by davide-q** [comment]
> i closed jupyterLab and restarted the pc and then it worked as expected. maybe that might help you too

Thanks for the suggestion. Besides this being on a server (not a PC), anyway a reboot did not help.

**Comment by ianhi** [comment]
Hi @davide-q 

is this running in a virtual environment (e.g. via conda/venv)? If so could you try in a freshly created environment to see if the issue persists?

When I create a new environment with: `conda create -n ipympl-test -c conda-forge jupyterlab ipympl` everything works for me with these versions:

```
 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
ipympl version: 0.9.3
Selected Jupyter core packages...
IPython          : 8.15.0
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.3.1
jupyter_core     : 5.3.1
jupyter_server   : 2.7.3
jupyterlab       : 4.0.6
nbclient         : 0.8.0
nbconvert        : 7.8.0
nbformat         : 5.9.2
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.10.0
JupyterLab v4.0.6
/home/ian/mambaforge/envs/ipympl-test/share/jupyter/labextensions
        jupyter-matplotlib v0.11.3 enabled OK
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)

/home/ian/.local/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.1 enabled  X


   The following extensions are outdated:
        jupyterlab_pygments
        nbdime-jupyterlab
        
   Consider checking if an update is available for these packages.
```


>  Wouldn't it be possible to provide a more meaningful error message that does not end up fooling google and providing outdated solutions of many, many versions ago?

Unfortunately that is not controlled by ipympl, rather by ipywidgets. You can see a PR that attempted to improve things here: https://github.com/jupyter-widgets/ipywidgets/pull/2960

**Comment by davide-q** [comment]
Thanks @ianhi -- yes, this is in a venv, and no creating a new one did not help (actually I had already tried that a few times, in case I was doing something incorrectly). 

At this point, I suspect the root cause is this server being behind a firewall (which I have no control of) that is blocking something. It would be good to know what that "something" is, so I could ask the network people if they are okay opening it....

Thanks for pointing me to the PR, hopefully we will eventually get good messages.

**Comment by ianhi** [comment]
A good thing to check is if there are errors in your browser console

**Comment by davide-q** [comment]
Thanks again @ianhi -- I don't think that provides any useful information, but here it is.

While trying to run this cell, which fails as shown

![image](https://github.com/matplotlib/ipympl/assets/106841869/b5825dac-5040-4f97-9178-c42ecd7c6f5f)

The chrome console reports

![image](https://github.com/matplotlib/ipympl/assets/106841869/28a36355-ff69-4699-8042-1fcc21d12d5f)

While the jupyter console reports

![image](https://github.com/matplotlib/ipympl/assets/106841869/b5747a8a-cc4a-44c0-9cc2-7bed939986f0)

As mentioned before in this ticket, the very same cell, on the very same jupyter install works just fine if I use the traditional interface rather than the jupyterlab by simply removing `lab` from the URL.

**Comment by itsmejoeeey** [comment]
I'm having this same issue too.

Environment:
```
Windows 11
`python`: 3.12.0
`pip`: 23.2.1
```

`requirements.txt`:
```
ipympl==0.9.3
notebook==7.0.6
matplotlib==3.8.2
```

Setup:
```
py -m venv .\.venv
.\.venv\Scripts\activate
pip install -r .\requirements.txt -y
jupyter notebook --notebook-dir=".\notebooks"
```

After opening my notebook:

![image](https://github.com/matplotlib/ipympl/assets/9375730/c89a21eb-c499-4bcc-a3c9-b229ae7bcb53)

Console errors:
```
Error: widget model not found
    get_model http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1
    renderModel http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1
[134.a63a8d293fb35a52dc25.js:1:72266](http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25)
    renderModel http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1
```

Please let me know if there is any further information I can provide.

**Comment by ogauthe** [comment]
Same problem here. `ipympl` can be loaded in console, not in jupyter lab. This prevents using `%matplotlib widget`.
Another user recently reported this in #132 .

**Comment by davide-q** [comment]
I still have not figured out why this is happening, but I re-installed everything in two different environments (server and kernel) and the reinstallation with the latest-and-greatest work. It would be nice to know what is causing the issue (which is still there in the old environments), but probably life's too short for that and having new environments where it work may be good enough for people.

**Comment by martinRenou** [comment]
Great that you could have an environment where it works. It's good to try with an environment with the least packages possible, and progressively install stuffs to find the culprit.

It turns out that some extensions like jupyter-bokeh breaks widgets as of today. Probably things will be better soonish.
