### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by astrozzj** [matplotlib/ipympl#557]
## Describe the issue

It always returns:

ERROR: Could not find a version that satisfies the requirement ipyml (from versions: none)
ERROR: No matching distribution found for ipyml

## Versions

```
 3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]
JupyterLab v4.1.4
/Users/zzj/Library/Python/3.11/share/jupyter/labextensions
        @jupyter-notebook/lab-extension v7.1.1 enabled OK
```

**Comment by martinRenou** [comment]
Can you please provide more information?
- the command you're running to install it
- the platform you're using
- the full error message

**Comment by astrozzj** [comment]
> Can you please provide more information?
> 
> * the command you're running to install it
> * the platform you're using
> * the full error message

command: pip3 install ipyml 
platform: MacBook Pro with M1 pro chip

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement ipyml (from versions: none)
ERROR: No matching distribution found for ipyml

The strange thing is I have jupyter-lab, but it seems I don't have 'jupyter'
